name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  # cypress-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - run: npm install
  #     - run: npm run fake-server &
  #     - run: npm run fake-server-graphql &

  #     - name: Cypress run
  #       uses: cypress-io/github-action@v1
  #       with:
  #         build: npm run build
  #         start: npm start
  #         wait-on: http://localhost:3000
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm run fake-server &
      - run: npm run fake-server-graphql &
      - run: npm test
        env:
          CI: true
